version: '3.8'

services:
  email-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"